### PR TITLE
Install a pprint-method that uses explain, in addition to the existing print-method

### LINKED ISSUE #277: StackOverflowError with s/protocol (when using io.aviso/pretty)
hi. 

bumped into this today:

```clj
lein try prismatic/schema

(require '[schema.core :as s])

(defprotocol Foo (foo [this]))

(s/validate (s/protocol Foo) 123)
; java.lang.StackOverflowError:
```

Am I doing something wrong here?

### PR DESCRIPTION
**Pull request by w01fe**
fixes #277 and possibly #275

### CODE REVIEW

**Comment by hlship** [comment]
That looks outstanding and should (I'll have to double check) work properly with io.aviso/pretty.

**Comment by w01fe** [comment]
Thanks @hlship !  Unfortunately, while the pprint method is working, it doesn't seem to fix the issue.  Any idea why?

```clojure
user=> (def e (try (s/validate (s/protocol Foo) 123) (catch Exception e e)))
#'user/e
user=> (clojure.pprint/pprint (ex-data e))
{:type :schema.core/error,
 :schema (protocol Foo),
 :value 123,
 :error (not (satisfies? Foo 123))}
nil
user=> (io.aviso.exception/write-exception e)
       clojure.core/eval                          core.clj: 3081
                     ...                                        
                 user/fn  form-init8972350361685322662.clj:    1
    schema.core/validate                          core.clj:  164
schema.core/validator/fn                          core.clj:  155
clojure.lang.ExceptionInfo: Value does not match schema: (not (satisfies? Foo 123))
     error: (not (satisfies? Foo 123))

... StackOverflow Error
```

**Comment by hlship** [comment]
I'm afraid it will be a couple of days before I can look at this; I'll pull down your branch and reproduce the error. I'm sure I can figure out what needs to change in Schema or pretty given a chance.

**Comment by w01fe** [comment]
No rush -- thanks a ton for your help with this!

**Comment by ikitommi** [comment]
Would be really nice if the printing & pretty-printing of schemas would use explain too in the the ClojureScript.

Currently:

```clj
(enable-console-print!)

(require '[schema.core :as s])

(s/defschema Kebab
  {:id s/Int
   :name s/Str
   :score (s/constrained s/Int #(>= 100 % 1) 'from1-100)
   :type (s/enum :doner :shish :souvlaki)
   :origin {:country (s/enum :FI :TR)}})

(cljs.pprint/pprint Kebab)

; ==>
{:id #schema.core.Predicate{:p? #object[cljs$core$integer_QMARK_ "function cljs$core$integer_QMARK_(n){
return (typeof n === 'number') && (!(isNaN(n))) && (!((n === Infinity))) && ((parseFloat(n) === parseInt(n,(10))));
}"], :pred-name cljs$core$integer?}, :name #schema.core.Predicate{:p? #object[cljs$core$string_QMARK_ "function cljs$core$string_QMARK_(x){
return goog.isString(x);
}"], :pred-name cljs$core$string?}, :score #schema.core.Constrained{:schema #schema.core.Predicate{:p? #object[cljs$core$integer_QMARK_ "function cljs$core$integer_QMARK_(n){
return (typeof n === 'number') && (!(isNaN(n))) && (!((n === Infinity))) && ((parseFloat(n) === parseInt(n,(10))));
}"], :pred-name cljs$core$integer?}, :postcondition #object[Function "function (p1__20877_SHARP_){
return (((100) >= p1__20877_SHARP_)) && ((p1__20877_SHARP_ >= (1)));
}"], :post-name from1-100}, :type #schema.core.EnumSchema{:vs #{:doner :shish :souvlaki}}, :origin {:country #schema.core.EnumSchema{:vs #{:FI :TR}}}
```

**Comment by ikitommi** [comment]
tested with code in this branch.

**Comment by w01fe** [comment]
Hi Tommi,

I agree,  I just don't know anything about the cljs printer. PR welcome!

-Jason

**Comment by hlship** [comment]
Looking into this now ...

**Comment by hlship** [comment]
I'm not certain exactly what's going on with this ... but I did create a 0.1.24 release of io.aviso/pretty that I *think* works around the problem properly.

**Comment by w01fe** [comment]
Thanks @hlship -- seems to work for me (at least outside of ultra)!

**Comment by ikitommi** [comment]
Clojurescript pretty-print requires some changes before it can be done. I can do PR when it's available

**Comment by w01fe** [comment]
@ikitommi that would be awesome, thanks!

**Pull request merged**
