### PR TITLE
Fixing advanced cljs compilation #417

### PR DESCRIPTION
**Pull request by oliyh**
Hi,

This fix worked for me in relation to #417 

Thanks,
Oliy

### CODE REVIEW

**Comment by gfredericks** [comment]
@w01fe this seems fine to me, do you have any objections?

**Comment by w01fe** [comment]
Yeah, seems fine if a bit unfortunate.  

I don't know enough about advanced compilation, is this going to be a problem in other places?  Maybe `pred` if passed a symbol should automatically capture the name or something?

**Comment by gfredericks** [comment]
I think it would be a problem in user code as well.

Automatically capturing the symbol would require converting `pred` into a macro, which would be a technically-breaking change, in that any weirdo doing higher-order stuff with it would have to refactor.

We could add a `(defmacro pred* [p] `(pred ~p '~p))`, and then people would have the option of using that. But that's complicated, requires explaining about why it's even necessary, etc..

**Comment by w01fe** [comment]
Yeah I agree the ship has sailed unfortunately. Thanks again!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gfredericks** [comment]
Also the macro approach would have edge cases like `(let [unhelpful-name integer?] (s/pred unhelpful-name))`.

**Comment by gfredericks** [comment]
Released as `1.1.12`.

**Pull request merged**
