### PR TITLE
cljx => cljc, no cljsee

### LINKED ISSUE #425: cjlx has been deprecated
Hi!

I'm working on packaging this program in Debian and it seems `schema` still depends on [cljx](https://github.com/lynaghk/cljx), that has been deprecated since at least 2016...

Are there any plans to move away from it and use `.cljc` instead? From a packaging point, it would be very helpful, as packaging deprecated software ain't great :( 

Thanks for working on `schema` !!

### PR DESCRIPTION
**Pull request by frenchy64**
Close #425 

Migrate cljx to cljc, which breaks support for Clojure 1.6.

### Reviewers

It is probably safe to hide whitespace changes, since some indentation changes were necessary.

There are several critical typos to look for:
1. `#(:clj ...)` instead of `#?(:clj ...)`
   - the former should never occur (missing `?`)
2. `#+clj a b c` should be converted to `#?(:clj a) b c`
   - NOT `#?(:clj a b c)`
3. Make sure `#+clj` corresponds to `#?(:clj)`, ditto for `cljs`
   - tags should be preserved

Any code that should not be compiled in js contexts in a cljc should be wrapped `#?(:clj)` (eg., `defmacro`, and macro helpers).

### Build
Added GitHub Actions matrix build to verify, see [results](https://github.com/frenchy64/schema/pull/1) on my fork (tests JVM 8+11+17).

Can remove if not wanted, as I know CircleCI is set up (but does not have a matrix build, or pr builds enabled).

### Temporary deployment
[Deployed](https://clojars.org/org.clojars.frenchy64/schema/versions/1.1.13-SNAPSHOT) jar at this commit: https://github.com/frenchy64/schema/commit/d8a5c08da87529ab9b01349f7dc3a2e6d43f9294
`[org.clojars.frenchy64/schema "1.1.13-20211021.171347-1"]`

### How to try:

Leiningen ([example](https://github.com/threatgrid/ctia/pull/1159/files))
```clojure
  :exclusions [prismatic/schema] ;; global exclusion
  :dependencies [[org.clojars.frenchy64/schema "1.1.13-20211021.171347-1"]]
```

Clojure CLI ([commit](https://github.com/frenchy64/schema/commit/ae728e11d9ced8756894a84fa3096826de73755d))
```clojure
  ;; deps.edn does not have a global override, git deps might be more reliable. if you use
  ;; the org.clojars.frenchy64/schema jar, inspect `clj -Stree` to ensure `prismatic/schema` is properly excluded.
  :deps {prismatic/schema {:git/url "https://github.com/frenchy64/schema.git"
                           :git/sha "ae728e11d9ced8756894a84fa3096826de73755d"}}
```

### Tasks:
- [x] try in Ambrose's production apps
   - [x] the big one
   - [x] https://github.com/threatgrid/ctia/pull/1159
- [ ] find someone who uses schema + cljs to try
- [x] try in schema-generators https://github.com/plumatic/schema-generators/pull/23

### CODE REVIEW

**Comment by loganlinn** [comment]
This is awesome. I'm happy to help review once ready!

**Comment by w01fe** [comment]
I believe it's enabled now, let me know if that did the trick or not.  

I think they were already enabled for contributors, so I'm not sure why it wasn't working (or if this actually fixed anything).

**Comment by frenchy64** [comment]
Yeah, how about we try and merge the build separately? It seems to work as-is https://github.com/plumatic/schema/pull/427

**Comment by w01fe** [comment]
Sorry for lagging on this, I was out of town and waiting to see if @loganlinn was going to review.  I looked it over and don't see any issues, so if I we don't hear from him in the next day or two I'll go ahead and merge.  Thanks!

**Review by loganlinn — APPROVED** [review]
I apologize for the delay. Everything looks great to me! I've tested this out on few other projects without any issue. Thanks again!

**Comment by w01fe** [comment]
Thanks a bunch for doing this!  I can cut a release if it would be helpful, let me know.

**Comment by frenchy64** [comment]
@w01fe yes please, I think this is worth a release.

**Comment by quoll** [comment]
Tested this on our code at work, with complete success.

**Pull request merged**
